name: Schema Check

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        id: Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env
        id: create-env
        run: echo "REACT_APP_VEGA_URL = http://n03.stagnet2.vega.xyz/query" > .env

      - name: Generate based on new schema
        run: |
          yarn install --frozen-lockfile
          yarn generate

      - name: Build app, to check for type errors
        run: |
          yarn build

      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_FRONTEND }}
        with:
          config: .github/slack-action-config/schema-bot.yml
          message:
            ":rotating_light: :rotating_light: :rotating_light: :rotating_light:


            @frontend


            Breaking changes between mainnet and stagnet2 detected.

            "
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: ${{ failure() }}
